Trait {
	#name : #SmockSymbologyManagerServices,
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : #'OpenSmock-SymbologyManager'
}

{ #category : #'services - symbology manager' }
SmockSymbologyManagerServices >> getCurrentSymbology [
]

{ #category : #'services - symbology manager' }
SmockSymbologyManagerServices >> getSymbol: aKey [

]

{ #category : #'services - symbology manager' }
SmockSymbologyManagerServices >> setCurrentSymbology: aKey [

]
