Class {
	#name : #SmockPickingElement,
	#superclass : #Object,
	#instVars : [
		'distanceInPixels',
		'dShape',
		'gShape',
		'layerLevel',
		'layerName',
		'objectKey',
		'object'
	],
	#category : #'OpenSmock-Core'
}

{ #category : #accessing }
SmockPickingElement >> dShape [
	^ dShape
]

{ #category : #accessing }
SmockPickingElement >> dShape: anObject [
	dShape := anObject
]

{ #category : #accessing }
SmockPickingElement >> distanceInPixels [
	^ distanceInPixels
]

{ #category : #accessing }
SmockPickingElement >> distanceInPixels: anObject [
	distanceInPixels := anObject
]

{ #category : #accessing }
SmockPickingElement >> gShape [
	^ gShape
]

{ #category : #accessing }
SmockPickingElement >> gShape: anObject [
	gShape := anObject
]

{ #category : #accessing }
SmockPickingElement >> layerLevel [
	^ layerLevel
]

{ #category : #accessing }
SmockPickingElement >> layerLevel: anObject [
	layerLevel := anObject
]

{ #category : #accessing }
SmockPickingElement >> layerName [
	^ layerName
]

{ #category : #accessing }
SmockPickingElement >> layerName: anObject [
	layerName := anObject
]

{ #category : #accessing }
SmockPickingElement >> object [

	^ object
]

{ #category : #accessing }
SmockPickingElement >> object: anObject [

	object := anObject
]

{ #category : #accessing }
SmockPickingElement >> objectKey [

	^ objectKey
]

{ #category : #accessing }
SmockPickingElement >> objectKey: anObject [

	objectKey := anObject
]
