Class {
	#name : #SmockViewUpdateChanges,
	#superclass : #Object,
	#category : #'OpenSmock-Model'
}

{ #category : #testing }
SmockViewUpdateChanges >> isBeVisibleChanges [

	^ false
]

{ #category : #testing }
SmockViewUpdateChanges >> isDisplayFilterChanges [

	^ false
]

{ #category : #testing }
SmockViewUpdateChanges >> isProjectionChanges [

	^ false
]

{ #category : #testing }
SmockViewUpdateChanges >> isSymbologyChanges [

	^ false
]

{ #category : #testing }
SmockViewUpdateChanges >> isViewInfosChanges [

	^ false
]
