Trait {
	#name : #TSmockHandleDShapes,
	#category : #'OpenSmock-Core'
}

{ #category : #'API -- DShapes' }
TSmockHandleDShapes >> addDShape: aDShape [

	self explicitRequirement
]

{ #category : #'API -- DShapes' }
TSmockHandleDShapes >> addDShapes: aDShapeList [

	self explicitRequirement
]

{ #category : #'API -- DShapes' }
TSmockHandleDShapes >> haveDShapeKey: aKey [

	self explicitRequirement
]

{ #category : #'API -- DShapes' }
TSmockHandleDShapes >> removeDShape: aDShape [

	self explicitRequirement
]

{ #category : #'API -- DShapes' }
TSmockHandleDShapes >> removeDShapes: aDShapeList [

	self explicitRequirement
]

{ #category : #'API -- DShapes' }
TSmockHandleDShapes >> updateDShape: aDShape [

	self explicitRequirement
]

{ #category : #'API -- DShapes' }
TSmockHandleDShapes >> updateDShapes: aDShapeList [

	self explicitRequirement
]
