Trait {
	#name : #SmockSelectionManagerServices,
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : #'OpenSmock-SelectionManager'
}

{ #category : #'services - selection manager' }
SmockSelectionManagerServices >> addSelectedKey: anObject [
]

{ #category : #'services - selection manager' }
SmockSelectionManagerServices >> addSelectedKeys: aCollection [
]

{ #category : #'services - selection manager' }
SmockSelectionManagerServices >> clearSelection [
]

{ #category : #'services - selection manager' }
SmockSelectionManagerServices >> getFirstSelectedKey [
]

{ #category : #'services - selection manager' }
SmockSelectionManagerServices >> getLastSelectedKey [
]

{ #category : #'services - selection manager' }
SmockSelectionManagerServices >> getSelectedKeys [
]

{ #category : #'services - selection manager' }
SmockSelectionManagerServices >> getSelectedKeysNb [
]

{ #category : #'services - selection manager - test' }
SmockSelectionManagerServices >> haveSelection [
]

{ #category : #'services - selection manager - test' }
SmockSelectionManagerServices >> isKeySelected: anObject [
]

{ #category : #'services - selection manager' }
SmockSelectionManagerServices >> removeSelectedKey: anObject [
]

{ #category : #'services - selection manager' }
SmockSelectionManagerServices >> removeSelectedKeys: aCollection [
]

{ #category : #'services - selection manager' }
SmockSelectionManagerServices >> setSelectedKey: anObject [
]

{ #category : #'services - selection manager' }
SmockSelectionManagerServices >> setSelectedKeys: aCollection [
]

{ #category : #'services - selection manager' }
SmockSelectionManagerServices >> xorSelectedKeys: aCollection [
]
