Class {
	#name : #SmockGPolyline2D,
	#superclass : #SmockGLeafShape2D,
	#instVars : [
		'points'
	],
	#category : #'OpenSmock-GShape'
}

{ #category : #testing }
SmockGPolyline2D >> isDrawable [ 

	self points ifNil: [ ^ false ].
	self points ifEmpty: [ ^ false ].

	^ super isDrawable
]

{ #category : #accessing }
SmockGPolyline2D >> points [

	^ points
]

{ #category : #accessing }
SmockGPolyline2D >> points: anObject [

	points := anObject
]
