Trait {
	#name : #TSmockHandleProcessDatas,
	#category : #'OpenSmock-Model'
}

{ #category : #'API -- process datas' }
TSmockHandleProcessDatas >> getAllProcessData [

	self explicitRequirement
]

{ #category : #'API -- process datas' }
TSmockHandleProcessDatas >> getDefaultProcessData [

	self explicitRequirement
]

{ #category : #'API -- process datas' }
TSmockHandleProcessDatas >> getProcessDataForClass: aGeoObjectClass [

	self explicitRequirement
]

{ #category : #'API -- process datas' }
TSmockHandleProcessDatas >> removeProcessDataForClass: aGeoObjectClass [

	self explicitRequirement
]

{ #category : #'API -- process datas' }
TSmockHandleProcessDatas >> setDefaultProcessData: aDataProcessor [

	self explicitRequirement
]

{ #category : #'API -- process datas' }
TSmockHandleProcessDatas >> setProcessData: aProcessData forClass: aGeoObjectClass [

	self explicitRequirement
]
