Trait {
	#name : #TSmockHandleObjects,
	#category : #'OpenSmock-Core'
}

{ #category : #'API -- objects management' }
TSmockHandleObjects >> addObject: aObject [

	self explicitRequirement
]

{ #category : #'API -- objects management' }
TSmockHandleObjects >> addObjects: anObjectList [

	self explicitRequirement
]

{ #category : #'API -- objects management' }
TSmockHandleObjects >> haveObjectIndex: anIndex [

	self explicitRequirement
]

{ #category : #'API -- objects management' }
TSmockHandleObjects >> removeObject: aObject [

	self explicitRequirement
]

{ #category : #'API -- objects management' }
TSmockHandleObjects >> removeObjects: anObjectList [

	self explicitRequirement
]

{ #category : #'API -- objects management' }
TSmockHandleObjects >> updateObject: aObject [

	self explicitRequirement
]

{ #category : #'API -- objects management' }
TSmockHandleObjects >> updateObjects: anObjectList [

	self explicitRequirement
]
